### ISSUE TITLE
vib.py is crashed

### ISSUE THREAD

**Issue by dizcza** [artemyk/nonlinearIB#3]
Does vib.py `main` section work?
`python vib.py 0.0`
```
/home/dizcza/anaconda3/envs/nonlinearIB/bin/python /home/dizcza/PycharmProjects/experiments/nonlinearIB/code/vib.py
/home/dizcza/anaconda3/envs/nonlinearIB/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Running variational IB with beta=0.00000
/home/dizcza/anaconda3/envs/nonlinearIB/lib/python2.7/site-packages/keras/engine/topology.py:638: UserWarning: Class `__main__.NoiseLayerVIB` defines `get_output_shape_for` but does not override `compute_output_shape`. If this is a Keras 1 layer, please implement `compute_output_shape` to support Keras 2.
  output_shape = self.compute_output_shape(input_shape)
/home/dizcza/PycharmProjects/experiments/nonlinearIB/code/vib.py:98: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(10, activation="softmax", kernel_initializer="he_uniform")`
  predictions = Dense(trn.nb_classes, init='he_uniform', activation='softmax')(c_layer)
Traceback (most recent call last):
  File "/home/dizcza/PycharmProjects/experiments/nonlinearIB/code/vib.py", line 98, in <module>
    predictions = Dense(trn.nb_classes, init='he_uniform', activation='softmax')(c_layer)
  File "/home/dizcza/anaconda3/envs/nonlinearIB/lib/python2.7/site-packages/keras/engine/topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/dizcza/anaconda3/envs/nonlinearIB/lib/python2.7/site-packages/keras/layers/core.py", line 855, in call
    output = K.dot(inputs, self.kernel)
  File "/home/dizcza/anaconda3/envs/nonlinearIB/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1075, in dot
    out = tf.matmul(x, y)
  File "/home/dizcza/anaconda3/envs/nonlinearIB/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 2064, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/home/dizcza/anaconda3/envs/nonlinearIB/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 2507, in _mat_mul
    name=name)
  File "/home/dizcza/anaconda3/envs/nonlinearIB/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/dizcza/anaconda3/envs/nonlinearIB/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3273, in create_op
    compute_device=compute_device)
  File "/home/dizcza/anaconda3/envs/nonlinearIB/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3313, in _create_op_helper
    set_shapes_for_outputs(op)
  File "/home/dizcza/anaconda3/envs/nonlinearIB/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2501, in set_shapes_for_outputs
    return _set_shapes_for_outputs(op)
  File "/home/dizcza/anaconda3/envs/nonlinearIB/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2474, in _set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/dizcza/anaconda3/envs/nonlinearIB/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2404, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/home/dizcza/anaconda3/envs/nonlinearIB/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "/home/dizcza/anaconda3/envs/nonlinearIB/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimensions must be equal, but are 256 and 512 for 'dense_4/MatMul' (op: 'MatMul') with input shapes: [?,256], [512,10].
```

**Comment by artemyk** [comment]
Thanks for the report!  vib.py has been updated to work with keras 2.0
